
---
title: "STAT 184 Final Project"
author: "Bernice Chen & Claudia Jung"
date: "December 17, 2019"
output: html_notebook
---


# Set Up

### Clean up environment and load packages
```{r}
# clean up the RStudio environment 
rm(list = ls())

# load all packages here: `mosaic`, `tidyverse`, `lubridate`, and all others used
library(mosaic)
library(tidyverse)
library(lubridate)
library(DataComputing)
library(ggplot2)
```

### Data Intake

```{r}
### Load the data set into our RStudio environment
Starbucks <- read.csv("StarbucksinCaliforniaCityStats.csv")

#commands used to inspect the data set
names(Starbucks)
View(Starbucks)

#adding the State column
Starbucks <-
  Starbucks %>%
  mutate(State="California")
```

### Research Question

#### Is there a relationship between number of Starbucks and demographic characteristics of a city?

Factors that we are interested:

- Age

- Median Income

- Percentage of White population

- Location

### Analysis- Age

```{r}
#Some of the variables provided wasn't numerical variable, needed to be converted
Starbucks$Median.Age <- as.numeric(as.character(Starbucks$Median.Age))
View(Starbucks)
#Checking if it's successfully converted
is.numeric(Starbucks$Median.Age)
#Plotting number of Starbucks vs Age
Starbucks %>%
  ggplot(aes(x=Median.Age, y=Number.of.Starbucks)) + geom_point() + ylim(0,50)
```
### Analysis- Median Income
```{r}
#Some of the variables provided wasn't numerical variable, needed to be converted
#Getting rid of $ and ,
Starbucks <-
  Starbucks %>%
  mutate(Median.Household.Income=gsub(pattern = "[$,]", replacement = "", Median.Household.Income))
#converting it into numerical variable
Starbucks$Median.Household.Income <- as.numeric(as.character(Starbucks$Median.Household.Income))
View(Starbucks)
#Checking if it's successfully converted
is.numeric(Starbucks$Median.Household.Income)
Starbucks %>%
  ggplot(aes(x=Median.Household.Income, y=Number.of.Starbucks)) + geom_point() + ylim(0,50)
```

### Analysis- White Population
```{r}
#Some of the variables provided wasn't numerical variable, needed to be converted
Starbucks$Percentage.of.white.population <- as.numeric(as.character(Starbucks$Percentage.of.white.population))
View(Starbucks)
#Checking if it's successfully converted
is.numeric(Starbucks$Percentage.of.white.population)
#Plotting number of Starbucks vs Percentage of White Population
Starbucks %>%
  ggplot(aes(x=Percentage.of.white.population, y=Number.of.Starbucks)) + geom_point() +ylim(0,50)

```


